import { SiteHeader } from "@/components/storefront/SiteHeader";
import { SiteFooter } from "@/components/storefront/SiteFooter";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Minus, Plus, Truck, GraduationCap, ArrowRight } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
const A="/editorial/b2b-launch/";
export default function B2BBook(){
 const [qty,setQty]=useState(1); const [educator,setEducator]=useState(false); const [done,setDone]=useState<string|number|null>(null);
 const [f,setF]=useState({firstName:"",lastName:"",email:"",phone:"",deliveryAddress:""});
 const order=trpc.site.orders.create.useMutation({onSuccess:(r:any)=>{setDone(r.orderNumber || r.orderId);toast.success("Commande enregistrée");},onError:()=>toast.error("Impossible d’enregistrer la commande.")});
 const submit=(e:React.FormEvent)=>{e.preventDefault();order.mutate({...f,quantity:qty,educator,productHandle:"b2b-brand-management",productTitle:"B2B Brand Management — Tunisia Edition"})};
 return <div className="min-h-screen bg-[#F7F4EE] text-[#171717]"><SiteHeader/><main>
 <section className="container grid gap-12 py-12 lg:grid-cols-[.9fr_1.1fr] lg:py-18"><div className="grid grid-cols-3 gap-3"><img src={A+"book-angle.jpg"} className="col-span-3 aspect-[4/5] w-full object-cover shadow-2xl"/><img src={A+"book-front.jpg"} className="aspect-[3/4] w-full object-cover"/><img src={A+"book-back.jpg"} className="aspect-[3/4] w-full object-cover"/><img src={A+"media.jpg"} className="aspect-[3/4] w-full object-cover"/></div><div className="lg:pt-5"><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#B71922]">Tunisia Edition</p><h1 className="mt-4 font-display text-[clamp(3.4rem,6vw,6.5rem)] leading-[.88] tracking-[-.05em]">B2B Brand Management</h1><p className="mt-5 text-lg font-semibold">Philip Kotler · Waldemar Pfoertsch · Walid Kallel</p><p className="mt-6 max-w-2xl text-base leading-7 text-black/60">Une édition tunisienne qui relie les fondamentaux internationaux du B2B Brand Management à des études de cas et à la réalité des organisations tunisiennes.</p><div className="mt-8 border-y border-black/10 py-6"><p className="text-xs font-extrabold uppercase tracking-[.15em] text-black/45">Paiement</p><p className="mt-2 flex items-center gap-2 font-semibold"><Truck className="h-5 w-5 text-[#B71922]"/>Paiement à la livraison</p><p className="mt-2 text-xs text-black/50">Aucun paiement en ligne. Vos coordonnées servent à confirmer et livrer votre commande.</p></div><a href="#commander" className="mt-8 inline-flex items-center gap-3 bg-[#B71922] px-7 py-4 text-[11px] font-extrabold uppercase tracking-[.15em] text-white">Commander le livre <ArrowRight className="h-4 w-4"/></a></div></section>
 <section className="border-y border-black/10 bg-white py-16"><div className="container"><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#B71922]">Case Studies · Tunisia Edition</p><h2 className="mt-3 font-display text-5xl">Les entreprises au cœur des cas.</h2><div className="mt-9 grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-7">{[{name:"BIAT",logo:"biat.jpg"},{name:"Wallyscar",logo:"wallyscar.jpg"},{name:"MSB",logo:"msb.jpg"},{name:"ARVEA",logo:"arvea.jpg"},{name:"Gourmandise",logo:"gourmandise.jpg"},{name:"MPBS",logo:"mpbs.jpg"},{name:"CHO Group",logo:"cho-group.jpg"}].map(x=><div className="flex min-h-32 flex-col items-center justify-center gap-3 border border-black/10 bg-[#F7F4EE] px-4 py-5 text-center" key={x.name}><img src={`/editorial/case-study-logos/${x.logo}`} alt={`Logo ${x.name}`} className="h-14 w-full object-contain mix-blend-multiply"/><span className="text-[10px] font-extrabold uppercase tracking-[.12em] text-black/50">{x.name}</span></div>)}</div></div></section>
 <section className="container py-16"><div className="grid overflow-hidden border border-[#B71922]/20 bg-white lg:grid-cols-2"><div className="p-8 md:p-12"><div className="inline-flex items-center gap-2 bg-[#B71922] px-3 py-2 text-[10px] font-extrabold uppercase tracking-[.16em] text-white"><GraduationCap className="h-4 w-4"/>Offre Educator</div><h2 className="mt-5 font-display text-4xl">Vous êtes enseignant ou formateur ?</h2><p className="mt-4 text-sm leading-7 text-black/60">À l’achat de ce livre, les enseignants et formateurs éligibles bénéficient de <strong>50 % de remise</strong> sur la version numérique de l’<em>Educator’s Guide & Case Study Companion — Tunisia Edition 2026</em>.</p></div><div className="bg-[#171717] p-10 text-white"><p className="font-display text-7xl text-[#DDA39B]">−50%</p><p className="mt-4 text-sm text-white/60">Avantage professionnel conditionné à l’achat du livre et au statut enseignant/formateur.</p></div></div></section>
 <section id="commander" className="border-t border-black/10 bg-[#171717] py-16 text-white"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[11px] font-extrabold uppercase tracking-[.2em] text-[#DDA39B]">Commande directe</p><h2 className="mt-4 font-display text-5xl">Commandez sur le site. Payez à la livraison.</h2><p className="mt-5 text-sm leading-7 text-white/60">Votre commande est enregistrée directement par L’Atelier des Pages. Nous utilisons vos coordonnées pour la confirmation et la livraison.</p></div>{done?<div className="bg-white p-10 text-[#171717]"><CheckCircle2 className="h-10 w-10 text-[#B71922]"/><h3 className="mt-5 font-display text-4xl">Commande reçue.</h3><p className="mt-3 text-sm text-black/60">Référence #{done}. Nous disposons des informations nécessaires pour confirmer votre commande et organiser la livraison.</p></div>:<form onSubmit={submit} className="bg-white p-7 text-[#171717] md:p-9"><div className="mb-7 flex items-center justify-between border-b border-black/10 pb-5"><div><p className="font-display text-2xl">B2B Brand Management</p><p className="text-xs text-black/50">Tunisia Edition · Paiement à la livraison</p></div><div className="flex items-center border border-black/15"><button type="button" onClick={()=>setQty(Math.max(1,qty-1))} className="p-3"><Minus className="h-4 w-4"/></button><span className="w-9 text-center font-bold">{qty}</span><button type="button" onClick={()=>setQty(Math.min(20,qty+1))} className="p-3"><Plus className="h-4 w-4"/></button></div></div><div className="grid gap-4 md:grid-cols-2"><Field label="Prénom" value={f.firstName} onChange={v=>setF({...f,firstName:v})}/><Field label="Nom" value={f.lastName} onChange={v=>setF({...f,lastName:v})}/><Field label="Adresse email" type="email" value={f.email} onChange={v=>setF({...f,email:v})}/><Field label="Téléphone" type="tel" value={f.phone} onChange={v=>setF({...f,phone:v})}/></div><label className="mt-4 block text-xs font-bold uppercase tracking-wide">Adresse de livraison<textarea required value={f.deliveryAddress} onChange={e=>setF({...f,deliveryAddress:e.target.value})} className="mt-2 min-h-28 w-full border border-black/15 bg-[#F7F4EE] p-3 text-sm font-normal outline-none focus:border-[#B71922]"/></label><label className="mt-5 flex items-start gap-3 bg-[#F7F4EE] p-4 text-sm"><input type="checkbox" checked={educator} onChange={e=>setEducator(e.target.checked)} className="mt-1"/><span><strong>Je suis enseignant ou formateur.</strong><br/><span className="text-xs text-black/55">Je souhaite bénéficier, après vérification de mon éligibilité et avec cet achat, de l’avantage Educator −50 % sur le Guide numérique.</span></span></label><button disabled={order.isPending} className="mt-6 w-full bg-[#B71922] px-6 py-4 text-xs font-extrabold uppercase tracking-[.15em] text-white disabled:opacity-50">{order.isPending?"Enregistrement…":"Confirmer ma commande · Paiement à la livraison"}</button></form>}</div></section>
 </main><SiteFooter/></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block text-xs font-bold uppercase tracking-wide">{label}<input required type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 h-12 w-full border border-black/15 bg-[#F7F4EE] px-3 text-sm font-normal outline-none focus:border-[#B71922]"/></label>}
